steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - '${_IMAGE}'
      - '--build-arg'
      - 'DATABASE_PROVIDER=${_DATABASE_PROVIDER}'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '${_IMAGE}'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_IMAGE}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - >-
        Database__Provider=${_DATABASE_PROVIDER},ConnectionStrings__DefaultConnection=${_CONNECTION_STRING}
substitutions:
  _IMAGE: gcr.io/$PROJECT_ID/puzzleam
  _SERVICE_NAME: puzzleam
  _REGION: us-central1
  _DATABASE_PROVIDER: Postgres
  _CONNECTION_STRING: Host=/cloudsql/PROJECT:REGION:INSTANCE;Database=puzzledb;Username=postgres;Password=CHANGE_ME
